name: deploy

on:
  push:
    tags: ['v*']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install wheel
        run: pip install wheel
      - name: Build MMEngine
        run: python -m pip wheel -e . --no-deps
      - name: Acquire version name
        run: |
          echo "${{ github.ref_name }}" | cut -c2- > version.txt
          echo "version=$(cat version.txt)" >> $GITHUB_ENV
      - name: Upload whl to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: 'mmengine-${{ env.version }}-py3-none-any.whl'
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: false
          body: mmengine auto release
