name: pr_stage_test

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true


on:
  pull_request:
    paths-ignore:
      - ".github/**.md"
      - "docker/**"
      - "docs/**"
      - "README.md"
      - "README_zh-CN.md"
      - "CONTRIBUTING.md"
      - "CONTRIBUTING_zh-CN.md"
      - ".pre-commit-config.yaml"
      - ".pre-commit-config-zh-cn.yaml"
      - "examples/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_gpu:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      MKL_THREADING_LAYER: GNU
    strategy:
      matrix:
        python-version: ['3.12', '3.13']
        torch: ['2.8.0']
        cuda: ['cu126']
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Setup uv
        uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        run: uv sync --extra=tests
      - name: Run unit tests with coverage
        run: uv run --extra=tests coverage run --branch --source mmengine -m pytest tests --ignore tests/test_dist
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
