name: pr_stage_test

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true


on:
  pull_request:
    paths-ignore:
      - ".github/**.md"
      - "docker/**"
      - "docs/**"
      - "README.md"
      - "README_zh-CN.md"
      - "CONTRIBUTING.md"
      - "CONTRIBUTING_zh-CN.md"
      - ".pre-commit-config.yaml"
      - ".pre-commit-config-zh-cn.yaml"
      - "examples/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_gpu:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    env:
      MKL_THREADING_LAYER: GNU
    strategy:
      matrix:
        python-version: ['3.11','3.12', '3.13']
        torch: ['2.6.0', '2.7.0', '2.8.0']
        cuda: ['cu126']
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Setup conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniconda-version: "latest"
          use-only-tar-bz2: true
          activate-environment: test
          python-version: ${{ matrix.python-version }}
      - name: Update pip
        run: |
          python -m pip install --upgrade pip wheel
      - name: Install dependencies
        run: |
          python -m pip install torch==${{matrix.torch}} --index-url https://download.pytorch.org/whl/${{matrix.cuda}}
          python -m pip install -e .[tests] -v
          python -m pip install mmcv+git@https://github.com/loseall/mmcv.git
      - name: Run unit tests with coverage
        run: coverage run --branch --source mmengine -m pytest tests/  --ignore tests/test_dist
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
